--select concat('grant execute on ',  r.ROUTINE_NAME , ' to adminrole')
--from INFORMATION_SCHEMA.ROUTINES r 

grant execute on CookbookDelete to adminrole
grant execute on CoursesDelete to adminrole
grant execute on RecipeIngredientsUpdate to adminrole
grant execute on IngredientDelete to adminrole
grant execute on IngredientUpdate to adminrole
grant execute on RecipeClone to adminrole
grant execute on IngredientsDelete to adminrole
grant execute on CookbookUpdate to adminrole
grant execute on CookbookRecipeUpdate to adminrole
grant execute on CookbookListGet to adminrole
grant execute on RecipeIngredientsGet to adminrole
grant execute on MeasurementUpdate to adminrole
grant execute on MeasurementDelete to adminrole
grant execute on RecipeIngredientGet to adminrole
grant execute on MeasurementsUpdate to adminrole
grant execute on RecipeIngredientDelete to adminrole
grant execute on CuisineTypeUpdate to adminrole
grant execute on UserUpdate to adminrole
grant execute on CookbookRecipeDelete to adminrole
grant execute on CookbookGet to adminrole
grant execute on RecipeIngredientsDelete to adminrole
grant execute on MeasurementsGet to adminrole
grant execute on RecipeDirectionsUpdate to adminrole
grant execute on CuisineTypeGet to adminrole
grant execute on UserGet to adminrole
grant execute on AutoCreateACookbook to adminrole
grant execute on RecipeGet to adminrole
grant execute on MeasurementsDelete to adminrole
grant execute on CuisineTypeDelete to adminrole
grant execute on TotalRecipesMealsCookbooksGet to adminrole
grant execute on MeasurementGet to adminrole
grant execute on RecipeDirectionsGet to adminrole
grant execute on MealListGet to adminrole
grant execute on RecipeIngredientUpdate to adminrole
grant execute on CoursesUpdate to adminrole
grant execute on RecipeUpdate to adminrole
grant execute on CookbookRecipeGet to adminrole
grant execute on RecipeDirectionsDelete to adminrole
grant execute on IngredientsUpdate to adminrole
grant execute on UserDelete to adminrole
grant execute on CoursesGet to adminrole
grant execute on RecipeListGet to adminrole
grant execute on CourseDelete to adminrole
grant execute on CourseGet to adminrole
grant execute on CourseUpdate to adminrole
grant execute on RecipeDelete to adminrole
grant execute on IngredientGet to adminrole